name: Build and Push Docker Image

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write

env:
  IMAGE_NAME: fastapi-app

jobs:
  bump-version:
    runs-on: ubuntu-latest
    outputs:
      new_version: ${{ steps.bump.outputs.new_version }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          persist-credentials: true # Ensure the token has write permissions

      - name: Read current version
        id: version
        run: echo "CURRENT_VERSION=$(cat VERSION)" >> $GITHUB_ENV

      - name: Bump version
        id: bump
        run: |
          CURRENT_VERSION=${{ env.CURRENT_VERSION }}
          BUMP_TYPE=$(git log -1 --pretty=%B | grep -oE 'bump: (major|minor|patch)' | cut -d' ' -f2 || echo 'patch')
          NEW_VERSION=$(echo $CURRENT_VERSION | awk -F. -v type=$BUMP_TYPE '{
            if (type == "major") { $1++; $2=0; $3=0 }
            else if (type == "minor") { $2++; $3=0 }
            else if (type == "patch") { $3++ }
            print $1"."$2"."$3
          }')

          if [ "$CURRENT_VERSION" != "$NEW_VERSION" ]; then
            echo "NEW_VERSION=$NEW_VERSION" >> $GITHUB_ENV
            echo $NEW_VERSION > VERSION
            echo "::set-output name=new_version::$NEW_VERSION"  # Set the output
          else
            echo "NEW_VERSION=$CURRENT_VERSION" >> $GITHUB_ENV
            echo "::set-output name=new_version::$CURRENT_VERSION"  # Set the output
          fi

      - name: Commit bumped version
        if: ${{ env.NEW_VERSION != env.CURRENT_VERSION }}
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add VERSION
          git commit -m "Bump version to ${{ env.NEW_VERSION }}"
          git push origin main

  build-and-push:
    runs-on: ubuntu-latest
    needs: bump-version
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.DOCKER_HUB_USERNAME }}/${{ env.IMAGE_NAME }}:${{ needs.bump-version.outputs.new_version }}
            ${{ secrets.DOCKER_HUB_USERNAME }}/${{ env.IMAGE_NAME }}:latest

      - name: Output Docker image details
        run: |
          IMAGE_NAME="${{ secrets.DOCKER_HUB_USERNAME }}/${{ env.IMAGE_NAME }}:${{ env.NEW_VERSION }}"
          DOCKER_HUB_LINK="https://hub.docker.com/r/${{ secrets.DOCKER_HUB_USERNAME }}/${{ env.IMAGE_NAME }}/tags"
          echo "### Docker Image Details" >> $GITHUB_STEP_SUMMARY
          echo "- **Image Name:** \`$IMAGE_NAME\`" >> $GITHUB_STEP_SUMMARY
          echo "- **Docker Hub Link:** [View on Docker Hub]($DOCKER_HUB_LINK)" >> $GITHUB_STEP_SUMMARY
