name: Python Tests

on:
  push:
    branches:
      - main
    paths:
      - app/**
      - tests/**
      - requirements-dev.txt
      - requirements.txt
      - pytest.ini
  workflow_dispatch:

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11" # Replace with your Python version (e.g., 3.11, 3.12)

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: venv
          key: venv-${{ runner.os }}-${{ hashFiles('requirements-dev.txt') }}
          restore-keys: |
            venv-${{ runner.os }}-

      - name: Install dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements-dev.txt

      - name: Run unit tests with coverage
        run: |
          source venv/bin/activate
          pytest tests/unit --cov=app --cov-report=xml:coverage-unit.xml

      - name: Upload unit test coverage report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-unit
          path: coverage-unit.xml

  integration-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: venv
          key: venv-${{ runner.os }}-${{ hashFiles('requirements-dev.txt') }}
          restore-keys: |
            venv-${{ runner.os }}-

      - name: Install dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements-dev.txt

      - name: Run integration tests with coverage
        run: |
          source venv/bin/activate
          pytest tests/integration --cov=app --cov-report=xml:coverage-integration.xml

      - name: Upload integration test coverage report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-integration
          path: coverage-integration.xml

  combine-coverage:
    runs-on: ubuntu-latest
    needs: [unit-tests, integration-tests]
    steps:
      - name: Download unit test coverage report
        uses: actions/download-artifact@v4
        with:
          name: coverage-unit
          path: coverage-reports

      - name: Download integration test coverage report
        uses: actions/download-artifact@v4
        with:
          name: coverage-integration
          path: coverage-reports

      - name: Combine coverage reports
        run: |
          pip install coverage
          coverage combine coverage-reports/coverage-unit.xml coverage-reports/coverage-integration.xml
          coverage xml -o combined-coverage.xml

      - name: Upload combined coverage report
        uses: actions/upload-artifact@v4
        with:
          name: combined-coverage
          path: combined-coverage.xml

      - name: Upload coverage to Codecov
        run: |
          source venv/bin/activate
          codecov --file=combined-coverage.xml
