name: Python Unit and Integration Tests

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Check out the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      # Create and activate a virtual environment
      - name: Create virtual environment
        run: python -m venv venv

      - name: Activate virtual environment
        run: source venv/bin/activate

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-dev.txt

      # Run unit tests with coverage
      - name: Run unit tests with coverage
        run: |
          pytest --cov=your_package_name tests/unit
          coverage xml -o coverage.xml

      # Upload coverage results to GitHub Actions summary
      - name: Upload coverage results to GitHub summary
        uses: actions/upload-artifact@v3
        with:
          name: coverage-report
          path: coverage.xml

      # Run integration tests
      - name: Run integration tests
        run: pytest tests/integration
